name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.2.4

permissions:
  contents: read
  id-token: write  # Required for npm authentication
  packages: write  # Required for GitHub Packages

jobs:
  # Pre-publish validation job
  validate:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build library
        run: npm run build:prod

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Verify package.json version matches tag
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION="${{ steps.version.outputs.VERSION }}"
          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: package.json version ($PACKAGE_VERSION) does not match tag version ($TAG_VERSION)"
            exit 1
          fi
          echo "✅ Version verification passed: $PACKAGE_VERSION"

  # Publish job that requires approval
  publish:
    runs-on: ubuntu-latest
    needs: validate
    environment: 
      name: github-packages-publish
      url: https://github.com/launchdarkly-labs/launchdarkly-angular/packages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build:prod

      - name: Publish to GitHub Packages
        run: cd dist/launchdarkly-angular && npm publish --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Changes in ${{ github.ref_name }}
            
            This release includes the following changes:
            
            ### Features
            - Add new features and improvements
            
            ### Bug Fixes
            - Fix various bugs and issues
            
            ### Documentation
            - Update documentation and examples
            
            ### Dependencies
            - Update dependencies to latest versions
            
            ---
            
            **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.ref_name }}
          draft: false
          prerelease: false
